name: 'Autograding Action'
description: 'Setup and test'
inputs:
  token:
    description: 'token'
    required: false
    default: ${{ github.token }}
outputs:
  GitHubClassroomWorkflow:
    description: "Points"
    value: ${{ steps.autograder.outputs.Points }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: DCI-EdTech/autograding@classes
      id: autograder
      with:
        token: ${{ inputs.token }}
        classes: "Autograding-Demo-Class;FbW-E05-B"
