name: 'Autograding Action'
description: 'Setup and test'
inputs:
  token:
    description: 'token'
    required: false
    default: ${{ github.token }}
outputs:
  GitHubClassroomWorkflow:
    description: "Points"
    value: ${{ steps.autograder.outputs.Points }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - uses: DCI-EdTech/autograding@cache
      id: autograder
      with:
        token: ${{ inputs.token }}
        classes: |
          Autograding-Demo-Class
          FbW-E05-B
          FBW-WD-22-D07
          22-d08-a
          FbW22-E10
