name: 'Autograding'
description: 'Setup and test'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: education/autograding@v1
      id: autograder
      
    - name: badges branch and make dir
      run: |
        git checkout --orphan badges
        git rm -rf .
        mkdir -p .github/badges
      shell: bash
