name: 'Autograding'
description: 'Setup and test'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: DCI-EdTech/autograding@main
      id: autograder
      
    - name: badges branch and make dir
      run: |
        git checkout --orphan badges
        git rm -rf .
        mkdir -p .github/badges
      shell: bash
      
    - name: points badge
      uses: emibcn/badge-action@v1
      with:
        LABEL: 'Points'
        STATUS: ${{ steps.autograder.outputs.points }}
        LABEL-COLOR: 2f496e
        COLOR: 2988bc
        SCALE: 2
        STYLE: flat
        path: '.github/badges/points.svg'
        
    - name: Upload badge as artifact
      uses: actions/upload-artifact@v2
      with:
        name: badge
        path: '.github/badges/points.svg'
        if-no-files-found: error
        retention-days: 1
        
    - name: Commit badge
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add '.github/badges/points.svg'
        git commit -m "Add/Update badge"
      shell: bash
      
    - name: Push badge commit
      uses: ad-m/github-push-action@master
      with:
        force: true
        github_token: ${{ github.token }}
        branch: badges
