name: 'Autograding Action'
description: 'Setup and test'
inputs:
  token:
    description: 'token'
    required: false
    default: ${{ github.token }}
outputs:
  GitHubClassroomWorkflow:
    description: "Points"
    value: ${{ steps.autograder.outputs.Points }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - uses: actions/cache@v3
      id: tmp-cache
      with:
        path: tmp
        key: ${{ runner.os }}-tmp-
        restore-keys: |
          ${{ runner.os }}-tmp-
    - uses: actions/cache@v3
      id: puppeteer-chromium-cache
      with:
        path: node_modules/puppeteer/.local-chromium
        key: ${{ runner.os }}-puppeteer-chromium-${{ hashFiles('node_modules/puppeteer/.local-chromium') }}
        restore-keys: |
          ${{ runner.os }}-puppeteer-chromium-
    - uses: DCI-EdTech/autograding@main
      id: autograder
      with:
        token: ${{ inputs.token }}
        classes: |
          Autograding-Demo-Class
          FbW-E05-B
          FBW-WD-22-D07
          22-d08-a
          FbW22-E10
