name: 'Autograding Action'
description: 'Setup and test'
inputs:
  token:
    description: 'gh token'
    required: false
    default: ${{ github.GITHUB_TOKEN }}
outputs:
  GitHubClassroomWorkflow:
    description: "Points"
    value: ${{ steps.autograder.outputs.Points }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ inputs.token }}

    - uses: DCI-EdTech/autograding@branch-protection
      id: autograder
      with:
        token: ${{ secrets.MAXIM }}
