name: 'Autograding Action'
description: 'Setup and test'
outputs:
  Autograding:
    description: "Points"
    value: ${{ steps.autograder.outputs.Points }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: DCI-EdTech/autograding@main
      id: autograder
      
    - name: "output"
      run: echo 'test'
